#!/usr/bin/env bash

### PedalPower Bootstrap

# This script will install the necessary dependencies, code and init scripts to run a pedalpower server node.
# It should only be run on a clean raspbian image, and only need to run if your config changes

### Configuration
# Set the hostname and static ip here
# Setup logfile
name='pedalpower-server'
export ip='10.0.0.10'

# Quit on error
set -e

# Our banner
echo
echo "Ｐｅｄａｌ  Ｐｏｗｅｒ  Ｆｏｏｔｓｔｒａｐ"
echo
# Expand to the entire sd card if we don't have at least 2 gigs free
size=`df -l | grep rootfs | awk '{ print $2 }'`
[[ $(($size - 1804128)) -lt 1804128 ]] && sudo raspi-config --expand-rootfs && sudo reboot

# Display colorized error output
function _error() {
    COLOR='\033[00;31m' # red
    RESET='\033[00;00m' # white
    echo -e "${COLOR}[PedalPower ERROR] ${@}${RESET}"
    exit 1
}

# Display colorized warning output
function _info() {
    COLOR='\033[00;32m' # green
    RESET='\033[00;00m' # white
    echo -e "${COLOR}[PedalPower INFO] ${@}${RESET}"
}


### Check that we have a network connection
_info "Checking for a network connection"
ping -c 5 google.com || _error "can't ping google"

### Permissions
# We ask for the administrator password upfront, and update a timestamp until
# the script is finished

sudo -v
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

### Install software dependencies


_info "Installing software dependencies"
_info "Updating software list"
sudo aptitude update
_info "Upgrading system software"
sudo aptitude upgrade -y
_info "Installing package dependencies"
sudo aptitude install -y rubygems
_info "Installing node.js 0.10.16"
if npm version 2>/dev/null
then
	_info "skipping node install"
else
	wget http://nodejs.org/dist/v0.10.16/node-v0.10.16-linux-arm-pi.tar.gz
    cd /usr/local
    sudo tar xzvf ~/node-v0.10.16-linux-arm-pi.tar.gz --strip=1
fi
_info "Installing libraries"
npm install

### Init scripts
# Generate the install initscripts using foreman

_info "Installing initscript"
initscript=`dirname $PWD`/venue-server/raspberrypi/venueserver
sudo cp $initscript /etc/init.d/ || _error "failed to copy initscript"
_info "Enabling initscript"
sudo update-rc.d venueserver defaults || _error "failed to enable initscript"

### Network config
# Each server node should have the same name and resolve to the same ip
# This is hardcoded in the software and this config script so that if a Pi
# fails, you can just pop in a new one and not miss a beat

# We do not error out on networking stuff because they produce errors
# on failed hostname lookup. That is to say, the ip and routing
# can be set fine and the ifconfig and route utilities still complain
# if the hostname is not in the router's lookup table. No big deal.

_info "Setting up networking"
_info "Setting hostname to ${name}"
oldname=`hostname`
export gateway='10.0.0.1'
export netmask='255.255.255.0'

sudo hostname ${name}
[[ -e /etc/hostname ]] || sudo touch /etc/hostname
sudo sed -ie "1s/.*/${name}/" /etc/hostname
sudo sed -ie "s/${oldname}/${name}/" /etc/hosts
_info "Setting ip to ${ip}, gateway to ${gateway}, netmask to ${netmask}"
sudo ifconfig eth0 ${ip} netmask ${netmask}
sudo route add default gw ${gateway}

# Make it permanent
sudo sed -ie '/eth0/d' /etc/network/interfaces
sudo tee -a /etc/network/interfaces << EOF

auto eth0
iface eth0 inet static
address ${ip}
netmask ${netmask}
gateway ${gateway}
EOF
_info "done!"