#! /bin/sh
# /etc/init.d/venueserver

### BEGIN INIT INFO
# Provides:          venueserver
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Simple script to start the venue server
# Description:       Thanks www.stuffaboutcode.com for the template
### END INIT INFO

set -e # exit on error

. /lib/lsb/init-functions

VENUESERVER_PID_FILE=/var/run/venueserver.pid

mkdir -p /var/log/venueserver

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    log_daemon_msg "Starting venueserver" "venueserver"
    start-stop-daemon --start --chdir /var/log/venueserver --startas /usr/local/bin/node --name venueserver --pidfile $VENUESERVER_PID_FILE --background -- /home/pi/venue-server/venue-server/src/app >> /var/log/venueserver.log 2>&1&
    log_end_msg $?
    ;;
  stop)
	log_daemon_msg "Stopping venuserver" "venuserver"
	start-stop-daemon --stop --quiet --oknodo --pidfile $VENUESERVER_PID_FILE
	log_end_msg $?
	rm -f $VENUESERVER_PID_FILE
	;;
  restart)
	log_daemon_msg "Restarting venuserver" "venuserver"
	stop
	start
	log_end_msg $?
	;;
  *)
    echo "Usage: /etc/init.d/venue-server {start|stop|restart}"
    exit 1
    ;;
esac

exit 0